account/urls.py
<<<<<<< HEAD
from django.conf.urls import url
from . import views

from django.conf import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r'^login/$', views.user_login, name='user_login'),      #自定义的登录
    url(r'^login/$', auth_views.login, name='user_login'),       #Django内置的登录
    url(r"^new-login/$", auth_views.login, {"template_name": "account/login.html"}),
    #url(r'^logout/$', auth_views.logout, name='user_logout'),
    url(r"^logout/$", auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
=======
from django.conf.urls import url
from . import views

from django.conf import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r'^login/$', views.user_login, name='user_login'),      #自定义的登录
    url(r'^login/$', auth_views.login, name='user_login'),       #Django内置的登录
    url(r"^new-login/$", auth_views.login, {"template_name": "account/login.html"}),
    #url(r'^logout/$', auth_views.logout, name='user_logout'),
    url(r"^logout/$", auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
    url(r'^register/$', views.register, name="user_register"),
    url(r'^password-change/$',auth_views.password_change,
        {"post_change_redirect":"account/password-change-done"},name='password_change'),
    url(r'^password-change-done/$',auth_views.password_change_done,name='password_change_done'),
    url(r'^password-reset/$',auth_views.password_reset,
        {'template_name':"account/password_reset_form.html",
         "email_template_name":"account/password_reset_email.html",
         "subject_template_name":"account/password_reset_subject.txt",
         "post_reset_redirect":"/account/password-reset-done"},name="password_reset"),
    url(r'^password-reset-done/$',auth_views.password_change_done,
        {"template_name":"account/password_reset_done.html"},name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.password_reset_confirm,
        {"template_name":"account/password_reset_confirm.html",
         "post_reset_redirect":"/account/password-reset-complete"},
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$',auth_views.password_reset_complete,
        {"template_name":"account/password_reset_complete.html"},
        name="password_reset_complete"),
>>>>>>> add 2.5
]

blog/urls.py
<<<<<<< HEAD
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
=======
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
>>>>>>> add 2.5
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/',include('account.urls', namespace='account',app_name='account')),
<<<<<<< HEAD
=======
    url(r'^pwd_reset/',include("password_reset.urls", namespace='pwd_reset',app_name='pwd_reset')),
>>>>>>> add 2.5
]

account/models.py
from django.db import models
<<<<<<< HEAD

# Create your models here.
=======
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, null=True)
    #email = models.EmailField(max_length=20, unique=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)
>>>>>>> add 2.5

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author =models.ForeignKey(User, related_name="blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

account/forms.py
<<<<<<< HEAD
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
=======
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("passwords do not match.")
        return cd["password2"]

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("phone", "birth")
        #fields =("phone", "birth", "email")
>>>>>>> add 2.5

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
<<<<<<< HEAD
from .forms import LoginForm
=======
from .forms import LoginForm, RegistrationForm, UserProfileForm
>>>>>>> add 2.5

# Create your views here.

def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user:
                login(request, user)
                return HttpResponse("Welcome You. You have been authenticated successfully")
            else:
                return HttpResponse("Sorry. Your username or password is not right.")
        else:
            return HttpResponse("Invalid login")

    if request.method == "GET":
        login_form = LoginForm()
<<<<<<< HEAD
        return render(request, "account/login.html", {"form": login_form})
=======
        return render(request, "account/login.html", {"form": login_form})

#def register(request):
#    if request.method == "POST":
#        user_form = RegistrationForm(request.POST)
#        if user_form.is_valid():
#            new_user = user_form.save(commit=False)
#            new_user.set_password(user_form.cleaned_data['password'])
#            new_user.save()
#            return HttpResponse("Successfull.")
#        else:
#            return HttpResponse("Sorry,your can not register.")
#    else:
#        user_form = RegistrationForm()
#        return render(request, "account/register.html", {"form": user_form})

def register(request):
    if request.method == "POST":
        user_form =RegistrationForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)
        if user_form.is_valid()*userprofile_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_profile = userprofile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return HttpResponse("successfully")
        else:
            return HttpResponse("sorry, your can not register.")

    else:
        user_form = RegistrationForm()
        userprofile_form = UserProfileForm()
        return render(request, "account/register.html", {"form": user_form,"profile": userprofile_form})
>>>>>>> add 2.5

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles

# Create your views here.

def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html", {"blogs":blogs})

def blog_article(request, article_id):
    #article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, "blog/content.html", {"article":article, "publish":pub})

templates/base.html
<<<<<<< HEAD
{% load staticfiles %}
<!--DOCTYPE html-->
<html lang="zh-cn">
<head>
    <!--meta http-equiv="X-UA-Compatible" content="IE=Edge"-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!--link rel="stylesheet" href="http://necolas.github.io/normalize.css/"-->
    <!--link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
<!--script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script-->
<!--script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script-->
</body>
=======
{% load staticfiles %}
<!--DOCTYPE html-->
<html lang="zh-cn">
<head>
    <!--meta http-equiv="X-UA-Compatible" content="IE=Edge"-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!--link rel="stylesheet" href="http://necolas.github.io/normalize.css/"-->
    <!--link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
<!--script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script-->
<!--script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script-->
</body>
>>>>>>> add 2.5
</html>

templates/blog/content.html
<<<<<<< HEAD
{% extends "base.html" %}

{% block title %}blog article{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-center"><span>{{    article.author.username    }}</span>
            <span style="margin-left: 20px">{{ publish }}</span></p>
        <div>{{ article.body }}</div>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>Advertising</h2>
        <p>from learn to laoqi: www.itdiffer.com</p>
        <img width="200px" src="https://b244.photo.store.qq.com/psb?/V14ObrhL2MY2gB/h*dDAHiKbAAHHZNLyMKcg58c7aG.lpqTU0xMDeftAAQ!/m/dPQAAAAAAAAAnull&bo=8ADwAAAAAAACByM!&rf=photolist&t=5">
    </div>
</div>
{% endblock %}
=======
{% extends "base.html" %}

{% block title %}blog article{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-center"><span>{{    article.author.username    }}</span>
            <span style="margin-left: 20px">{{ publish }}</span></p>
        <div>{{ article.body }}</div>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>Advertising</h2>
        <p>from learn to laoqi: www.itdiffer.com</p>
        <img width="200px" src="https://b244.photo.store.qq.com/psb?/V14ObrhL2MY2gB/h*dDAHiKbAAHHZNLyMKcg58c7aG.lpqTU0xMDeftAAQ!/m/dPQAAAAAAAAAnull&bo=8ADwAAAAAAACByM!&rf=photolist&t=5">
    </div>
</div>
{% endblock %}
>>>>>>> add 2.5
<!--http://www.mrwallpaper.com/wallpapers/Fluffy-Cat.jpg>

templates/blog/titles.html
<<<<<<< HEAD
{% extends "base.html" %}

{% block title %}blog titles{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>my blog</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <ul>
            {% for blog in blogs %}
                <li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>advertising</h2>
        <p>from learn to laoqi: www.itdiffer.com</p>
        <img width="2000px" src="http://www.mrwallpaper.com/wallpapers/Fluffy-Cat.jpg">
    </div>
</div>
{% endblock %}
=======
{% extends "base.html" %}

{% block title %}blog titles{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>my blog</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <ul>
            {% for blog in blogs %}
                <li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>advertising</h2>
        <p>from learn to laoqi: www.itdiffer.com</p>
        <img width="2000px" src="http://www.mrwallpaper.com/wallpapers/Fluffy-Cat.jpg">
    </div>
</div>
{% endblock %}
>>>>>>> add 2.5
<!--blog/static/grwordcloud.png>

templates/footer.html
<<<<<<< HEAD
<div class="container">
    <hr>
    <p class="text-center">copy right www.itdiffer.com</p>
=======
<div class="container">
    <hr>
    <p class="text-center">copy right www.itdiffer.com</p>
>>>>>>> add 2.5
</div>

templates/header.html
<<<<<<< HEAD
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com">
                <img src="{% static '/images/logo.jpg' %}" width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if user.is_authenticated %}
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
=======
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com">
                <img src="{% static '/images/logos.jpg' %}" width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                data-toggle="dropdown">{{ user.username }}<span class="caret"></span> </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">change password</a></li>
                        </ul>
                    </div>
                </li>
                <!--li><a href="#">{{ user.username }}</a></li-->
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
>>>>>>> add 2.5

templates/password_reset/base.html
{% extends "base.html" %}

templates/password_reset/recovery_done.html
{% extends "password_reset/base.html" %}{% load i18n %}

{% block title %}{% trans "New password set" %}{% endblock %}

{% block content %}
	<p>{% trans "Your password has successfully been reset. You can use it right now on the login page." %}</p>
{% endblock %}

templates/password_reset/recovery_form.html
{% extends "password_reset/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password recovery" %}{% endblock %}

{% block content %}
	<form method="post" action="{{ url }}">
		{% csrf_token %}
		{{ form.as_p }}
		<p><input type="submit" value="{% trans "Recover my password" %}"></p>
	</form>
{% endblock %}

templates/password_reset/reset.html
{% extends "password_reset/base.html" %}{% load i18n %}

{% block content %}
	{% if invalid %}{% url "password_reset_recover" as recovery_url %}
		<p>{% blocktrans %}Sorry, this password reset link is invalid. You can still <a href="{{ recovery_url }}">request a new one</a>.{% endblocktrans %}</p>
	{% else %}
		<p>{% blocktrans %}Hi, <strong>{{ username }}</strong>. Please choose your new password.{% endblocktrans %}</p>
		<form method="post" action="{% url "password_reset_reset" token %}">
			{% csrf_token %}
			{{ form.as_p }}
			<p><input type="submit" value="{% trans "Set new password" %}"></p>
		</form>
	{% endif %}
{% endblock %}

templates/password_reset/reset_sent.html
{% extends "password_reset/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password recovery sent" %}{% endblock %}

{% block content %}
	<p>{% blocktrans with ago=timestamp|timesince %}An email was sent to <strong>{{ email }}</strong> {{ ago }} ago. Use the link in it to set a new password.{% endblocktrans %}</p>
{% endblock %}